### ISSUE TITLE
ULDK error

### ISSUE THREAD

**Issue by wuwik** [envirosolutionspl/uldk_gugik#72]
Witam,
Przy próbie uruchomienia wtyczki ULDK_GUGIK wyskakuje błąd:

Nie można wczytać wtyczki 'uldk_gugik' z powodu błędu wywołania jej metody classFactory() 

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='uldk.gugik.gov.pl', port=443): Max retries exceeded with url: /service.php?obiekt=wojewodztwo&wynik=wojewodztwo,teryt (Caused by NameResolutionError(": Failed to resolve 'uldk.gugik.gov.pl' ([Errno 11001] getaddrinfo failed)")) 

Poproszę o pomoc.
Anna

**Comment by wojtek19022** [comment]
Dzień dobry, proszę o informację, czy podczas włączania QGIS był włączony internet. Jeżeli wtyczka nie ma połączenia z internetem, to bardzo możliwe że taki błąd wyskoczy :) 
Poprawimy obsługę sprawdzenia braku połączenia z internetem przy włączaniu QGIS na tyle ile nam pozwala API PyQGIS
